# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test123' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'ReactiveObjC', '~> 3.1.1'
pod 'AFNetworking'

  # Pods for test123

  target 'test123Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test123UITests' do
    # Pods for testing
  end

end
